package com.roborally.server.service;

import java.util.Locale;

/**
 * Direct extraction of the old single-board RoboRally maps.
 *
 * <p>These ops intentionally stay in legacy coordinates/orientations so BoardLoader owns the only
 * coordinate/orientation adapter.</p>
 */
enum LegacyOrientation {
    LEFT, RIGHT, TOP, BOTTOM
}

enum LegacyOpKind {
    WALL, PIT, REPAIR, CHECKPOINT, CONVEYOR, CURVE, CROSSING, GEAR, PUSHER, PRESS, LASER
}

record LegacyOp(LegacyOpKind kind, int x, int y, LegacyOrientation orientation, int value, boolean express) {
}

record LegacyBoardSpec(LegacyOp[] ops, int totalCheckpoints) {
}

final class LegacyBoardSpecs {
    private LegacyBoardSpecs() {
    }

    static LegacyBoardSpec forName(String boardName) {
        String normalizedName = boardName == null ? "map1" : boardName.toLowerCase(Locale.ROOT);
        return switch (normalizedName) {
            case "map2" -> MAP2;
            case "map3" -> MAP3;
            case "map4" -> MAP4;
            case "map5" -> MAP5;
            case "map6" -> MAP6;
            default -> MAP1;
        };
    }

    private static LegacyBoardSpec spec(LegacyOp... ops) {
        return new LegacyBoardSpec(ops, 2);
    }

    private static LegacyOp wall(int x, int y, LegacyOrientation orientation) {
        return new LegacyOp(LegacyOpKind.WALL, x, y, orientation, 0, false);
    }

    private static LegacyOp pit(int x, int y) {
        return new LegacyOp(LegacyOpKind.PIT, x, y, null, 0, false);
    }

    private static LegacyOp repair(int x, int y, int level) {
        return new LegacyOp(LegacyOpKind.REPAIR, x, y, null, level, false);
    }

    private static LegacyOp checkpoint(int x, int y, int number) {
        return new LegacyOp(LegacyOpKind.CHECKPOINT, x, y, null, number, false);
    }

    private static LegacyOp conveyor(int x, int y, LegacyOrientation orientation, boolean express) {
        return new LegacyOp(LegacyOpKind.CONVEYOR, x, y, orientation, 0, express);
    }

    private static LegacyOp curve(int x, int y, LegacyOrientation orientation, int curve, boolean express) {
        return new LegacyOp(LegacyOpKind.CURVE, x, y, orientation, curve, express);
    }

    private static LegacyOp crossing(int x, int y, LegacyOrientation orientation, int crossing, boolean express) {
        return new LegacyOp(LegacyOpKind.CROSSING, x, y, orientation, crossing, express);
    }

    private static LegacyOp gear(int x, int y, LegacyOrientation orientation) {
        return new LegacyOp(LegacyOpKind.GEAR, x, y, orientation, 0, false);
    }

    private static LegacyOp pusher(int x, int y, LegacyOrientation orientation, int activeStep) {
        return new LegacyOp(LegacyOpKind.PUSHER, x, y, orientation, activeStep, false);
    }

    private static LegacyOp press(int x, int y, int activeStep) {
        return new LegacyOp(LegacyOpKind.PRESS, x, y, null, activeStep, false);
    }

    private static LegacyOp laser(int x, int y, LegacyOrientation orientation, int power) {
        return new LegacyOp(LegacyOpKind.LASER, x, y, orientation, power, false);
    }

    static final LegacyBoardSpec MAP1 = spec(
            wall(2, 0, LegacyOrientation.BOTTOM),
            wall(4, 0, LegacyOrientation.BOTTOM),
            conveyor(5, 0, LegacyOrientation.BOTTOM, false),
            conveyor(6, 0, LegacyOrientation.TOP, false),
            wall(7, 0, LegacyOrientation.BOTTOM),
            wall(9, 0, LegacyOrientation.BOTTOM),
            curve(10, 0, LegacyOrientation.TOP, 2, false),
            curve(11, 0, LegacyOrientation.RIGHT, 1, false),
            conveyor(0, 1, LegacyOrientation.RIGHT, false),
            curve(1, 1, LegacyOrientation.RIGHT, 1, false),
            wall(3, 1, LegacyOrientation.RIGHT),
            wall(4, 1, LegacyOrientation.LEFT),
            conveyor(5, 1, LegacyOrientation.BOTTOM, false),
            conveyor(6, 1, LegacyOrientation.TOP, false),
            wall(7, 1, LegacyOrientation.RIGHT),
            wall(8, 1, LegacyOrientation.LEFT),
            repair(10, 1, 1),
            wall(10, 1, LegacyOrientation.TOP),
            curve(11, 1, LegacyOrientation.TOP, 2, false),
            wall(0, 2, LegacyOrientation.LEFT),
            conveyor(1, 2, LegacyOrientation.TOP, false),
            pit(3, 2),
            wall(3, 2, LegacyOrientation.TOP),
            conveyor(5, 2, LegacyOrientation.BOTTOM, false),
            conveyor(6, 2, LegacyOrientation.TOP, false),
            wall(6, 2, LegacyOrientation.RIGHT),
            wall(7, 2, LegacyOrientation.LEFT),
            pit(9, 2),
            wall(10, 2, LegacyOrientation.RIGHT),
            wall(10, 2, LegacyOrientation.BOTTOM),
            wall(11, 2, LegacyOrientation.LEFT),
            wall(11, 2, LegacyOrientation.RIGHT),
            wall(0, 3, LegacyOrientation.TOP),
            conveyor(1, 3, LegacyOrientation.TOP, false),
            wall(2, 3, LegacyOrientation.TOP),
            wall(3, 3, LegacyOrientation.BOTTOM),
            conveyor(5, 3, LegacyOrientation.BOTTOM, false),
            conveyor(6, 3, LegacyOrientation.TOP, false),
            wall(7, 3, LegacyOrientation.RIGHT),
            wall(8, 3, LegacyOrientation.LEFT),
            wall(10, 3, LegacyOrientation.RIGHT),
            wall(11, 3, LegacyOrientation.LEFT),
            wall(0, 4, LegacyOrientation.LEFT),
            wall(0, 4, LegacyOrientation.BOTTOM),
            conveyor(1, 4, LegacyOrientation.TOP, false),
            wall(2, 4, LegacyOrientation.BOTTOM),
            wall(3, 4, LegacyOrientation.TOP),
            wall(4, 4, LegacyOrientation.TOP),
            wall(4, 4, LegacyOrientation.RIGHT),
            conveyor(5, 4, LegacyOrientation.BOTTOM, false),
            wall(5, 4, LegacyOrientation.LEFT),
            curve(6, 4, LegacyOrientation.TOP, 2, false),
            curve(7, 4, LegacyOrientation.RIGHT, 1, false),
            wall(7, 4, LegacyOrientation.RIGHT),
            wall(8, 4, LegacyOrientation.LEFT),
            wall(8, 4, LegacyOrientation.TOP),
            wall(9, 4, LegacyOrientation.TOP),
            wall(11, 4, LegacyOrientation.RIGHT),
            conveyor(0, 5, LegacyOrientation.RIGHT, false),
            crossing(1, 5, LegacyOrientation.RIGHT, 2, false),
            conveyor(2, 5, LegacyOrientation.RIGHT, false),
            conveyor(3, 5, LegacyOrientation.RIGHT, false),
            wall(3, 5, LegacyOrientation.BOTTOM),
            conveyor(4, 5, LegacyOrientation.RIGHT, false),
            wall(4, 5, LegacyOrientation.BOTTOM),
            curve(5, 5, LegacyOrientation.RIGHT, 2, false),
            pit(6, 5),
            curve(7, 5, LegacyOrientation.TOP, 2, false),
            conveyor(8, 5, LegacyOrientation.RIGHT, false),
            wall(8, 5, LegacyOrientation.BOTTOM),
            conveyor(9, 5, LegacyOrientation.RIGHT, false),
            wall(9, 5, LegacyOrientation.BOTTOM),
            conveyor(10, 5, LegacyOrientation.RIGHT, false),
            conveyor(11, 5, LegacyOrientation.RIGHT, false),
            conveyor(0, 6, LegacyOrientation.LEFT, false),
            conveyor(1, 6, LegacyOrientation.LEFT, false),
            conveyor(2, 6, LegacyOrientation.LEFT, false),
            conveyor(3, 6, LegacyOrientation.LEFT, false),
            curve(4, 6, LegacyOrientation.BOTTOM, 2, false),
            pit(5, 6),
            pit(6, 6),
            pit(7, 6),
            curve(8, 6, LegacyOrientation.LEFT, 2, false),
            conveyor(9, 6, LegacyOrientation.LEFT, false),
            crossing(10, 6, LegacyOrientation.LEFT, 2, false),
            conveyor(11, 6, LegacyOrientation.LEFT, false),
            wall(0, 7, LegacyOrientation.LEFT),
            wall(3, 7, LegacyOrientation.TOP),
            wall(3, 7, LegacyOrientation.RIGHT),
            curve(4, 7, LegacyOrientation.LEFT, 1, false),
            wall(4, 7, LegacyOrientation.LEFT),
            curve(5, 7, LegacyOrientation.BOTTOM, 2, false),
            pit(6, 7),
            curve(7, 7, LegacyOrientation.LEFT, 2, false),
            curve(8, 7, LegacyOrientation.TOP, 1, false),
            wall(8, 7, LegacyOrientation.TOP),
            wall(8, 7, LegacyOrientation.RIGHT),
            wall(9, 7, LegacyOrientation.LEFT),
            conveyor(10, 7, LegacyOrientation.BOTTOM, false),
            wall(11, 7, LegacyOrientation.RIGHT),
            wall(3, 8, LegacyOrientation.BOTTOM),
            wall(3, 8, LegacyOrientation.RIGHT),
            wall(4, 8, LegacyOrientation.LEFT),
            conveyor(5, 8, LegacyOrientation.BOTTOM, false),
            curve(6, 8, LegacyOrientation.LEFT, 2, false),
            curve(7, 8, LegacyOrientation.TOP, 1, false),
            wall(7, 8, LegacyOrientation.TOP),
            wall(7, 8, LegacyOrientation.RIGHT),
            wall(8, 8, LegacyOrientation.LEFT),
            wall(8, 8, LegacyOrientation.BOTTOM),
            conveyor(10, 8, LegacyOrientation.BOTTOM, false),
            wall(0, 9, LegacyOrientation.LEFT),
            pit(1, 9),
            wall(1, 9, LegacyOrientation.RIGHT),
            wall(2, 9, LegacyOrientation.LEFT),
            wall(3, 9, LegacyOrientation.TOP),
            wall(4, 9, LegacyOrientation.RIGHT),
            conveyor(5, 9, LegacyOrientation.BOTTOM, false),
            wall(5, 9, LegacyOrientation.LEFT),
            conveyor(6, 9, LegacyOrientation.TOP, false),
            pit(7, 9),
            wall(7, 9, LegacyOrientation.BOTTOM),
            wall(8, 9, LegacyOrientation.TOP),
            repair(9, 9, 2),
            conveyor(10, 9, LegacyOrientation.BOTTOM, false),
            wall(11, 9, LegacyOrientation.RIGHT),
            conveyor(0, 10, LegacyOrientation.LEFT, false),
            curve(1, 10, LegacyOrientation.BOTTOM, 2, false),
            wall(3, 10, LegacyOrientation.RIGHT),
            wall(3, 10, LegacyOrientation.BOTTOM),
            wall(4, 10, LegacyOrientation.LEFT),
            conveyor(5, 10, LegacyOrientation.BOTTOM, false),
            conveyor(6, 10, LegacyOrientation.TOP, false),
            pit(7, 10),
            wall(7, 10, LegacyOrientation.RIGHT),
            wall(8, 10, LegacyOrientation.LEFT),
            wall(8, 10, LegacyOrientation.BOTTOM),
            curve(10, 10, LegacyOrientation.LEFT, 1, false),
            conveyor(11, 10, LegacyOrientation.LEFT, false),
            pit(0, 11),
            conveyor(1, 11, LegacyOrientation.BOTTOM, false),
            repair(3, 10, 1),
            wall(2, 11, LegacyOrientation.TOP),
            wall(4, 11, LegacyOrientation.TOP),
            conveyor(5, 11, LegacyOrientation.BOTTOM, false),
            conveyor(6, 11, LegacyOrientation.TOP, false),
            wall(7, 11, LegacyOrientation.TOP),
            wall(9, 11, LegacyOrientation.TOP),
            checkpoint(1, 7, 1),
            checkpoint(8, 4, 2),
            laser(8, 3, LegacyOrientation.RIGHT, 2),
            laser(3, 4, LegacyOrientation.BOTTOM, 1),
            laser(9, 7, LegacyOrientation.RIGHT, 1),
            laser(3, 9, LegacyOrientation.BOTTOM, 1)
    );

    static final LegacyBoardSpec MAP2 = spec(
            wall(1, 0, LegacyOrientation.TOP),
            wall(2, 0, LegacyOrientation.BOTTOM),
            conveyor(3, 0, LegacyOrientation.TOP, false),
            wall(4, 0, LegacyOrientation.BOTTOM),
            conveyor(5, 0, LegacyOrientation.BOTTOM, true),
            wall(7, 0, LegacyOrientation.BOTTOM),
            conveyor(8, 0, LegacyOrientation.BOTTOM, false),
            wall(9, 0, LegacyOrientation.BOTTOM),
            conveyor(10, 0, LegacyOrientation.TOP, false),
            pit(0, 1),
            wall(1, 1, LegacyOrientation.BOTTOM),
            wall(2, 1, LegacyOrientation.RIGHT),
            conveyor(3, 1, LegacyOrientation.TOP, false),
            wall(3, 1, LegacyOrientation.LEFT),
            conveyor(5, 1, LegacyOrientation.BOTTOM, true),
            conveyor(6, 1, LegacyOrientation.TOP, false),
            conveyor(8, 1, LegacyOrientation.BOTTOM, false),
            repair(10, 1, 1),
            conveyor(11, 1, LegacyOrientation.RIGHT, false),
            wall(0, 2, LegacyOrientation.LEFT),
            conveyor(3, 2, LegacyOrientation.TOP, false),
            conveyor(5, 2, LegacyOrientation.BOTTOM, true),
            conveyor(6, 2, LegacyOrientation.TOP, false),
            conveyor(8, 2, LegacyOrientation.BOTTOM, false),
            wall(10, 2, LegacyOrientation.TOP),
            wall(11, 2, LegacyOrientation.RIGHT),
            conveyor(0, 3, LegacyOrientation.LEFT, false),
            conveyor(1, 3, LegacyOrientation.LEFT, false),
            conveyor(2, 3, LegacyOrientation.LEFT, false),
            gear(3, 3, LegacyOrientation.LEFT),
            conveyor(5, 3, LegacyOrientation.BOTTOM, true),
            conveyor(6, 3, LegacyOrientation.TOP, false),
            gear(8, 3, LegacyOrientation.LEFT),
            conveyor(9, 3, LegacyOrientation.LEFT, false),
            conveyor(10, 3, LegacyOrientation.LEFT, false),
            wall(10, 3, LegacyOrientation.BOTTOM),
            conveyor(11, 3, LegacyOrientation.LEFT, false),
            wall(0, 4, LegacyOrientation.LEFT),
            wall(4, 4, LegacyOrientation.TOP),
            wall(4, 4, LegacyOrientation.RIGHT),
            conveyor(5, 4, LegacyOrientation.BOTTOM, true),
            wall(5, 4, LegacyOrientation.LEFT),
            conveyor(6, 4, LegacyOrientation.TOP, false),
            wall(6, 4, LegacyOrientation.RIGHT),
            repair(7, 4, 2),
            wall(7, 4, LegacyOrientation.TOP),
            wall(7, 4, LegacyOrientation.LEFT),
            wall(11, 4, LegacyOrientation.RIGHT),
            conveyor(1, 5, LegacyOrientation.RIGHT, false),
            conveyor(2, 5, LegacyOrientation.RIGHT, false),
            conveyor(3, 5, LegacyOrientation.RIGHT, false),
            conveyor(4, 5, LegacyOrientation.RIGHT, false),
            wall(4, 5, LegacyOrientation.BOTTOM),
            conveyor(7, 5, LegacyOrientation.RIGHT, true),
            wall(7, 5, LegacyOrientation.BOTTOM),
            conveyor(8, 5, LegacyOrientation.RIGHT, true),
            conveyor(9, 5, LegacyOrientation.RIGHT, true),
            conveyor(10, 5, LegacyOrientation.RIGHT, true),
            conveyor(11, 5, LegacyOrientation.RIGHT, true),
            conveyor(0, 6, LegacyOrientation.LEFT, false),
            conveyor(1, 6, LegacyOrientation.LEFT, false),
            conveyor(2, 6, LegacyOrientation.LEFT, false),
            conveyor(3, 6, LegacyOrientation.LEFT, false),
            conveyor(4, 6, LegacyOrientation.LEFT, false),
            wall(4, 6, LegacyOrientation.TOP),
            conveyor(7, 6, LegacyOrientation.LEFT, false),
            wall(7, 6, LegacyOrientation.TOP),
            conveyor(8, 6, LegacyOrientation.LEFT, false),
            conveyor(9, 6, LegacyOrientation.LEFT, false),
            conveyor(10, 6, LegacyOrientation.LEFT, false),
            conveyor(11, 6, LegacyOrientation.LEFT, false),
            wall(0, 7, LegacyOrientation.LEFT),
            wall(4, 7, LegacyOrientation.BOTTOM),
            wall(4, 7, LegacyOrientation.RIGHT),
            conveyor(5, 7, LegacyOrientation.BOTTOM, false),
            wall(5, 7, LegacyOrientation.LEFT),
            conveyor(6, 7, LegacyOrientation.TOP, false),
            wall(6, 7, LegacyOrientation.RIGHT),
            wall(7, 7, LegacyOrientation.BOTTOM),
            wall(7, 7, LegacyOrientation.LEFT),
            wall(11, 7, LegacyOrientation.RIGHT),
            conveyor(0, 8, LegacyOrientation.RIGHT, false),
            conveyor(1, 8, LegacyOrientation.RIGHT, false),
            conveyor(2, 8, LegacyOrientation.RIGHT, false),
            gear(3, 8, LegacyOrientation.LEFT),
            conveyor(5, 8, LegacyOrientation.BOTTOM, false),
            conveyor(6, 8, LegacyOrientation.TOP, false),
            conveyor(8, 8, LegacyOrientation.BOTTOM, false),
            conveyor(9, 8, LegacyOrientation.RIGHT, true),
            conveyor(10, 8, LegacyOrientation.RIGHT, true),
            conveyor(11, 8, LegacyOrientation.RIGHT, true),
            wall(0, 9, LegacyOrientation.LEFT),
            conveyor(3, 9, LegacyOrientation.TOP, false),
            conveyor(5, 9, LegacyOrientation.BOTTOM, false),
            conveyor(6, 9, LegacyOrientation.TOP, false),
            conveyor(8, 9, LegacyOrientation.BOTTOM, false),
            wall(8, 9, LegacyOrientation.RIGHT),
            wall(9, 9, LegacyOrientation.LEFT),
            wall(11, 9, LegacyOrientation.RIGHT),
            conveyor(0, 10, LegacyOrientation.LEFT, false),
            repair(1, 10, 1),
            pit(2, 10),
            conveyor(3, 10, LegacyOrientation.TOP, false),
            conveyor(5, 10, LegacyOrientation.BOTTOM, false),
            conveyor(6, 10, LegacyOrientation.TOP, false),
            conveyor(8, 10, LegacyOrientation.BOTTOM, false),
            gear(10, 10, LegacyOrientation.RIGHT),
            conveyor(11, 10, LegacyOrientation.LEFT, false),
            wall(2, 11, LegacyOrientation.TOP),
            conveyor(3, 11, LegacyOrientation.TOP, false),
            wall(4, 11, LegacyOrientation.TOP),
            conveyor(5, 11, LegacyOrientation.BOTTOM, false),
            conveyor(6, 11, LegacyOrientation.TOP, false),
            wall(7, 11, LegacyOrientation.TOP),
            conveyor(8, 11, LegacyOrientation.BOTTOM, false),
            wall(9, 11, LegacyOrientation.TOP),
            conveyor(10, 11, LegacyOrientation.TOP, false),
            checkpoint(2, 2, 1),
            checkpoint(9, 10, 2),
            laser(11, 9, LegacyOrientation.LEFT, 1)
    );

    static final LegacyBoardSpec MAP3 = spec(
            wall(2, 0, LegacyOrientation.BOTTOM),
            wall(4, 0, LegacyOrientation.BOTTOM),
            wall(7, 0, LegacyOrientation.BOTTOM),
            wall(9, 0, LegacyOrientation.BOTTOM),
            pit(1, 1),
            pit(2, 1),
            pit(9, 1),
            pit(10, 1),
            wall(0, 2, LegacyOrientation.LEFT),
            pit(1, 2),
            gear(2, 2, LegacyOrientation.RIGHT),
            conveyor(3, 2, LegacyOrientation.LEFT, false),
            conveyor(4, 2, LegacyOrientation.LEFT, false),
            conveyor(5, 2, LegacyOrientation.LEFT, false),
            wall(5, 2, LegacyOrientation.TOP),
            conveyor(6, 2, LegacyOrientation.LEFT, false),
            conveyor(7, 2, LegacyOrientation.LEFT, false),
            conveyor(8, 2, LegacyOrientation.LEFT, false),
            conveyor(9, 2, LegacyOrientation.BOTTOM, false),
            pit(10, 2),
            wall(11, 2, LegacyOrientation.RIGHT),
            conveyor(2, 3, LegacyOrientation.TOP, false),
            gear(3, 3, LegacyOrientation.LEFT),
            conveyor(4, 3, LegacyOrientation.RIGHT, false),
            crossing(5, 3, LegacyOrientation.RIGHT, 1, false),
            conveyor(6, 3, LegacyOrientation.RIGHT, false),
            conveyor(7, 3, LegacyOrientation.RIGHT, false),
            gear(8, 3, LegacyOrientation.LEFT),
            conveyor(9, 3, LegacyOrientation.BOTTOM, false),
            wall(0, 4, LegacyOrientation.LEFT),
            conveyor(2, 4, LegacyOrientation.TOP, false),
            conveyor(3, 4, LegacyOrientation.BOTTOM, false),
            conveyor(5, 4, LegacyOrientation.BOTTOM, false),
            pit(6, 4),
            pit(7, 4),
            conveyor(8, 4, LegacyOrientation.TOP, false),
            conveyor(9, 4, LegacyOrientation.BOTTOM, false),
            repair(10, 4, 1),
            wall(11, 4, LegacyOrientation.RIGHT),
            conveyor(2, 5, LegacyOrientation.TOP, false),
            wall(2, 5, LegacyOrientation.RIGHT),
            conveyor(3, 5, LegacyOrientation.BOTTOM, false),
            wall(3, 5, LegacyOrientation.LEFT),
            conveyor(5, 5, LegacyOrientation.BOTTOM, false),
            pit(7, 5),
            conveyor(8, 5, LegacyOrientation.TOP, false),
            wall(8, 5, LegacyOrientation.RIGHT),
            conveyor(9, 5, LegacyOrientation.BOTTOM, false),
            wall(9, 5, LegacyOrientation.LEFT),
            conveyor(2, 6, LegacyOrientation.TOP, false),
            conveyor(3, 6, LegacyOrientation.BOTTOM, false),
            pit(4, 6),
            conveyor(6, 6, LegacyOrientation.TOP, false),
            conveyor(8, 6, LegacyOrientation.TOP, false),
            conveyor(9, 6, LegacyOrientation.BOTTOM, false),
            wall(0, 7, LegacyOrientation.LEFT),
            repair(1, 7, 1),
            conveyor(2, 7, LegacyOrientation.TOP, false),
            conveyor(3, 7, LegacyOrientation.BOTTOM, false),
            pit(4, 7),
            pit(5, 7),
            conveyor(6, 7, LegacyOrientation.TOP, false),
            repair(7, 7, 2),
            conveyor(8, 7, LegacyOrientation.TOP, false),
            conveyor(9, 7, LegacyOrientation.BOTTOM, false),
            wall(11, 7, LegacyOrientation.RIGHT),
            conveyor(2, 8, LegacyOrientation.TOP, false),
            gear(3, 8, LegacyOrientation.LEFT),
            conveyor(4, 8, LegacyOrientation.LEFT, false),
            conveyor(5, 8, LegacyOrientation.LEFT, false),
            crossing(6, 8, LegacyOrientation.LEFT, 1, false),
            wall(6, 8, LegacyOrientation.TOP),
            conveyor(7, 8, LegacyOrientation.LEFT, false),
            gear(8, 8, LegacyOrientation.LEFT),
            conveyor(9, 8, LegacyOrientation.BOTTOM, false),
            wall(0, 9, LegacyOrientation.LEFT),
            pit(1, 9),
            gear(2, 9, LegacyOrientation.RIGHT),
            conveyor(3, 9, LegacyOrientation.RIGHT, false),
            conveyor(4, 9, LegacyOrientation.RIGHT, false),
            conveyor(5, 9, LegacyOrientation.RIGHT, false),
            conveyor(6, 9, LegacyOrientation.RIGHT, false),
            wall(6, 9, LegacyOrientation.BOTTOM),
            conveyor(7, 9, LegacyOrientation.RIGHT, false),
            conveyor(8, 9, LegacyOrientation.RIGHT, false),
            conveyor(9, 9, LegacyOrientation.RIGHT, false),
            pit(10, 9),
            wall(11, 9, LegacyOrientation.RIGHT),
            pit(1, 10),
            pit(2, 10),
            pit(9, 10),
            pit(10, 10),
            wall(2, 11, LegacyOrientation.TOP),
            wall(4, 11, LegacyOrientation.TOP),
            wall(7, 11, LegacyOrientation.TOP),
            wall(9, 11, LegacyOrientation.TOP),
            checkpoint(4, 1, 1),
            checkpoint(8, 10, 2)
    );

    static final LegacyBoardSpec MAP4 = spec(
            conveyor(1, 2, LegacyOrientation.TOP, false),
            conveyor(1, 3, LegacyOrientation.TOP, false),
            conveyor(1, 4, LegacyOrientation.TOP, false),
            conveyor(1, 5, LegacyOrientation.TOP, false),
            conveyor(1, 6, LegacyOrientation.TOP, false),
            conveyor(1, 7, LegacyOrientation.TOP, false),
            conveyor(1, 8, LegacyOrientation.TOP, false),
            conveyor(1, 9, LegacyOrientation.TOP, false),
            crossing(1, 5, LegacyOrientation.TOP, 1, false),
            conveyor(2, 2, LegacyOrientation.TOP, true),
            conveyor(2, 3, LegacyOrientation.TOP, true),
            conveyor(2, 4, LegacyOrientation.TOP, true),
            conveyor(2, 5, LegacyOrientation.TOP, true),
            conveyor(2, 6, LegacyOrientation.TOP, true),
            conveyor(2, 7, LegacyOrientation.TOP, true),
            conveyor(2, 8, LegacyOrientation.TOP, true),
            wall(2, 5, LegacyOrientation.RIGHT),
            conveyor(3, 3, LegacyOrientation.TOP, false),
            conveyor(3, 4, LegacyOrientation.TOP, false),
            conveyor(3, 5, LegacyOrientation.TOP, false),
            conveyor(3, 6, LegacyOrientation.TOP, false),
            conveyor(3, 7, LegacyOrientation.TOP, false),
            wall(3, 5, LegacyOrientation.LEFT),
            wall(3, 6, LegacyOrientation.RIGHT),
            conveyor(4, 4, LegacyOrientation.TOP, true),
            conveyor(4, 5, LegacyOrientation.TOP, true),
            conveyor(4, 6, LegacyOrientation.TOP, true),
            wall(4, 6, LegacyOrientation.LEFT),
            conveyor(10, 2, LegacyOrientation.BOTTOM, true),
            conveyor(10, 3, LegacyOrientation.BOTTOM, true),
            conveyor(10, 4, LegacyOrientation.BOTTOM, true),
            conveyor(10, 5, LegacyOrientation.BOTTOM, true),
            conveyor(10, 6, LegacyOrientation.BOTTOM, true),
            conveyor(10, 7, LegacyOrientation.BOTTOM, true),
            conveyor(10, 8, LegacyOrientation.BOTTOM, true),
            conveyor(10, 9, LegacyOrientation.BOTTOM, true),
            crossing(10, 6, LegacyOrientation.BOTTOM, 1, true),
            conveyor(9, 3, LegacyOrientation.BOTTOM, false),
            conveyor(9, 4, LegacyOrientation.BOTTOM, false),
            conveyor(9, 5, LegacyOrientation.BOTTOM, false),
            conveyor(9, 6, LegacyOrientation.BOTTOM, false),
            conveyor(9, 7, LegacyOrientation.BOTTOM, false),
            conveyor(9, 8, LegacyOrientation.BOTTOM, false),
            conveyor(9, 9, LegacyOrientation.BOTTOM, false),
            wall(9, 6, LegacyOrientation.LEFT),
            conveyor(8, 4, LegacyOrientation.BOTTOM, true),
            conveyor(8, 5, LegacyOrientation.BOTTOM, true),
            conveyor(8, 6, LegacyOrientation.BOTTOM, true),
            conveyor(8, 7, LegacyOrientation.BOTTOM, true),
            conveyor(8, 8, LegacyOrientation.BOTTOM, true),
            wall(8, 6, LegacyOrientation.RIGHT),
            conveyor(7, 5, LegacyOrientation.BOTTOM, false),
            conveyor(7, 6, LegacyOrientation.BOTTOM, false),
            conveyor(7, 7, LegacyOrientation.BOTTOM, false),
            wall(7, 5, LegacyOrientation.RIGHT),
            wall(8, 5, LegacyOrientation.LEFT),
            conveyor(3, 1, LegacyOrientation.LEFT, true),
            conveyor(4, 1, LegacyOrientation.LEFT, true),
            conveyor(5, 1, LegacyOrientation.LEFT, true),
            conveyor(6, 1, LegacyOrientation.LEFT, true),
            conveyor(7, 1, LegacyOrientation.LEFT, true),
            conveyor(8, 1, LegacyOrientation.LEFT, true),
            conveyor(9, 1, LegacyOrientation.LEFT, true),
            crossing(6, 1, LegacyOrientation.LEFT, 1, true),
            conveyor(4, 2, LegacyOrientation.LEFT, false),
            conveyor(5, 2, LegacyOrientation.LEFT, false),
            conveyor(6, 2, LegacyOrientation.LEFT, false),
            conveyor(7, 2, LegacyOrientation.LEFT, false),
            conveyor(8, 2, LegacyOrientation.LEFT, false),
            wall(6, 2, LegacyOrientation.TOP),
            wall(6, 3, LegacyOrientation.BOTTOM),
            conveyor(5, 3, LegacyOrientation.LEFT, true),
            conveyor(6, 3, LegacyOrientation.LEFT, true),
            conveyor(7, 3, LegacyOrientation.LEFT, true),
            conveyor(2, 10, LegacyOrientation.RIGHT, false),
            conveyor(3, 10, LegacyOrientation.RIGHT, false),
            conveyor(4, 10, LegacyOrientation.RIGHT, false),
            conveyor(5, 10, LegacyOrientation.RIGHT, false),
            conveyor(6, 10, LegacyOrientation.RIGHT, false),
            conveyor(7, 10, LegacyOrientation.RIGHT, false),
            conveyor(8, 10, LegacyOrientation.RIGHT, false),
            crossing(5, 10, LegacyOrientation.RIGHT, 1, false),
            conveyor(3, 9, LegacyOrientation.RIGHT, true),
            conveyor(4, 9, LegacyOrientation.RIGHT, true),
            conveyor(5, 9, LegacyOrientation.RIGHT, true),
            conveyor(6, 9, LegacyOrientation.RIGHT, true),
            conveyor(7, 9, LegacyOrientation.RIGHT, true),
            conveyor(4, 8, LegacyOrientation.RIGHT, false),
            conveyor(5, 8, LegacyOrientation.RIGHT, false),
            conveyor(6, 8, LegacyOrientation.RIGHT, false),
            pusher(2, 0, LegacyOrientation.BOTTOM, 4),
            pusher(4, 0, LegacyOrientation.BOTTOM, 0),
            conveyor(5, 0, LegacyOrientation.BOTTOM, false),
            conveyor(6, 0, LegacyOrientation.TOP, true),
            pusher(7, 0, LegacyOrientation.BOTTOM, 0),
            pusher(9, 0, LegacyOrientation.BOTTOM, 4),
            conveyor(10, 0, LegacyOrientation.TOP, true),
            conveyor(0, 1, LegacyOrientation.RIGHT, false),
            curve(1, 1, LegacyOrientation.RIGHT, 1, false),
            curve(2, 1, LegacyOrientation.LEFT, 2, true),
            crossing(10, 1, LegacyOrientation.LEFT, 3, true),
            pusher(0, 2, LegacyOrientation.LEFT, 4),
            curve(3, 2, LegacyOrientation.LEFT, 2, false),
            curve(9, 2, LegacyOrientation.BOTTOM, 2, false),
            pusher(11, 2, LegacyOrientation.RIGHT, 4),
            curve(4, 3, LegacyOrientation.LEFT, 2, true),
            curve(8, 3, LegacyOrientation.BOTTOM, 2, true),
            pusher(0, 4, LegacyOrientation.LEFT, 0),
            curve(5, 4, LegacyOrientation.LEFT, 2, false),
            conveyor(6, 4, LegacyOrientation.LEFT, false),
            curve(7, 4, LegacyOrientation.BOTTOM, 2, false),
            pusher(11, 4, LegacyOrientation.RIGHT, 0),
            conveyor(0, 5, LegacyOrientation.RIGHT, false),
            pit(5, 5),
            pit(6, 5),
            conveyor(0, 6, LegacyOrientation.LEFT, false),
            pit(5, 6),
            pit(6, 6),
            conveyor(11, 6, LegacyOrientation.LEFT, true),
            pusher(0, 7, LegacyOrientation.LEFT, 0),
            curve(4, 7, LegacyOrientation.TOP, 2, true),
            conveyor(5, 7, LegacyOrientation.RIGHT, true),
            curve(6, 7, LegacyOrientation.RIGHT, 2, true),
            pusher(11, 7, LegacyOrientation.RIGHT, 0),
            curve(3, 8, LegacyOrientation.TOP, 2, false),
            curve(7, 8, LegacyOrientation.RIGHT, 2, false),
            pusher(0, 9, LegacyOrientation.LEFT, 4),
            curve(2, 9, LegacyOrientation.TOP, 2, true),
            curve(8, 9, LegacyOrientation.RIGHT, 2, true),
            pusher(11, 9, LegacyOrientation.RIGHT, 4),
            crossing(1, 10, LegacyOrientation.RIGHT, 3, false),
            curve(9, 10, LegacyOrientation.RIGHT, 2, false),
            curve(10, 10, LegacyOrientation.LEFT, 1, true),
            conveyor(11, 10, LegacyOrientation.LEFT, true),
            conveyor(1, 11, LegacyOrientation.BOTTOM, false),
            pusher(2, 11, LegacyOrientation.TOP, 4),
            pusher(4, 11, LegacyOrientation.TOP, 0),
            conveyor(5, 11, LegacyOrientation.BOTTOM, false),
            pusher(7, 11, LegacyOrientation.TOP, 0),
            pusher(9, 11, LegacyOrientation.TOP, 4),
            checkpoint(1, 1, 1),
            checkpoint(8, 8, 2),
            laser(7, 5, LegacyOrientation.LEFT, 1),
            laser(8, 6, LegacyOrientation.LEFT, 1)
    );

    static final LegacyBoardSpec MAP5 = spec(
            conveyor(0, 0, LegacyOrientation.TOP, true),
            wall(2, 0, LegacyOrientation.BOTTOM),
            wall(2, 0, LegacyOrientation.TOP),
            curve(4, 0, LegacyOrientation.BOTTOM, 1, false),
            wall(4, 0, LegacyOrientation.BOTTOM),
            curve(5, 0, LegacyOrientation.RIGHT, 2, false),
            crossing(6, 0, LegacyOrientation.TOP, 2, false),
            conveyor(7, 0, LegacyOrientation.LEFT, true),
            wall(7, 0, LegacyOrientation.BOTTOM),
            conveyor(8, 0, LegacyOrientation.LEFT, true),
            wall(8, 0, LegacyOrientation.TOP),
            conveyor(9, 0, LegacyOrientation.LEFT, true),
            wall(9, 0, LegacyOrientation.BOTTOM),
            crossing(10, 0, LegacyOrientation.LEFT, 1, true),
            wall(10, 0, LegacyOrientation.TOP),
            conveyor(11, 0, LegacyOrientation.LEFT, true),
            crossing(0, 1, LegacyOrientation.TOP, 1, true),
            repair(1, 1, 1),
            wall(2, 1, LegacyOrientation.BOTTOM),
            wall(3, 1, LegacyOrientation.RIGHT),
            conveyor(4, 1, LegacyOrientation.BOTTOM, false),
            wall(4, 1, LegacyOrientation.LEFT),
            wall(4, 1, LegacyOrientation.RIGHT),
            pusher(5, 1, LegacyOrientation.LEFT, 3),
            wall(5, 1, LegacyOrientation.LEFT),
            press(6, 1, 1),
            wall(8, 1, LegacyOrientation.BOTTOM),
            repair(9, 1, 2),
            wall(9, 1, LegacyOrientation.TOP),
            wall(9, 1, LegacyOrientation.RIGHT),
            wall(10, 1, LegacyOrientation.LEFT),
            wall(10, 1, LegacyOrientation.BOTTOM),
            conveyor(11, 1, LegacyOrientation.TOP, false),
            conveyor(0, 2, LegacyOrientation.TOP, true),
            wall(0, 2, LegacyOrientation.LEFT),
            wall(1, 2, LegacyOrientation.TOP),
            wall(1, 2, LegacyOrientation.RIGHT),
            wall(2, 2, LegacyOrientation.LEFT),
            wall(3, 2, LegacyOrientation.BOTTOM),
            conveyor(4, 2, LegacyOrientation.BOTTOM, false),
            wall(5, 2, LegacyOrientation.TOP),
            conveyor(6, 2, LegacyOrientation.TOP, false),
            wall(7, 2, LegacyOrientation.TOP),
            wall(7, 2, LegacyOrientation.RIGHT),
            pusher(8, 2, LegacyOrientation.LEFT, 2),
            wall(9, 2, LegacyOrientation.TOP),
            wall(9, 2, LegacyOrientation.BOTTOM),
            pusher(10, 2, LegacyOrientation.RIGHT, 1),
            wall(10, 2, LegacyOrientation.RIGHT),
            conveyor(11, 2, LegacyOrientation.TOP, false),
            wall(11, 2, LegacyOrientation.RIGHT),
            conveyor(0, 3, LegacyOrientation.TOP, true),
            wall(1, 3, LegacyOrientation.BOTTOM),
            wall(2, 3, LegacyOrientation.RIGHT),
            wall(2, 3, LegacyOrientation.TOP),
            wall(3, 3, LegacyOrientation.LEFT),
            wall(3, 3, LegacyOrientation.RIGHT),
            conveyor(4, 3, LegacyOrientation.BOTTOM, false),
            wall(4, 3, LegacyOrientation.LEFT),
            repair(5, 3, 2),
            conveyor(6, 3, LegacyOrientation.TOP, false),
            wall(7, 3, LegacyOrientation.BOTTOM),
            pit(9, 3),
            wall(9, 3, LegacyOrientation.BOTTOM),
            wall(10, 3, LegacyOrientation.TOP),
            crossing(11, 3, LegacyOrientation.TOP, 2, false),
            conveyor(0, 4, LegacyOrientation.TOP, true),
            wall(0, 4, LegacyOrientation.RIGHT),
            wall(1, 4, LegacyOrientation.LEFT),
            wall(1, 4, LegacyOrientation.TOP),
            wall(2, 4, LegacyOrientation.BOTTOM),
            wall(3, 4, LegacyOrientation.TOP),
            press(4, 4, 2),
            conveyor(5, 4, LegacyOrientation.LEFT, false),
            conveyor(6, 4, LegacyOrientation.TOP, false),
            conveyor(9, 4, LegacyOrientation.BOTTOM, true),
            wall(10, 4, LegacyOrientation.BOTTOM),
            conveyor(11, 4, LegacyOrientation.TOP, false),
            crossing(0, 5, LegacyOrientation.RIGHT, 2, true),
            conveyor(1, 5, LegacyOrientation.RIGHT, true),
            wall(1, 5, LegacyOrientation.BOTTOM),
            conveyor(2, 5, LegacyOrientation.RIGHT, true),
            wall(2, 5, LegacyOrientation.TOP),
            conveyor(3, 5, LegacyOrientation.RIGHT, true),
            wall(3, 5, LegacyOrientation.BOTTOM),
            crossing(4, 5, LegacyOrientation.BOTTOM, 2, false),
            conveyor(5, 5, LegacyOrientation.RIGHT, false),
            press(6, 5, 3),
            conveyor(8, 5, LegacyOrientation.RIGHT, true),
            curve(9, 5, LegacyOrientation.RIGHT, 2, true),
            curve(11, 5, LegacyOrientation.TOP, 2, false),
            wall(1, 6, LegacyOrientation.TOP),
            wall(2, 6, LegacyOrientation.BOTTOM),
            repair(5, 6, 2),
            wall(3, 6, LegacyOrientation.TOP),
            conveyor(4, 6, LegacyOrientation.TOP, false),
            crossing(6, 6, LegacyOrientation.TOP, 2, false),
            conveyor(7, 6, LegacyOrientation.LEFT, true),
            pusher(8, 6, LegacyOrientation.TOP, 2),
            conveyor(9, 6, LegacyOrientation.LEFT, true),
            conveyor(10, 6, LegacyOrientation.LEFT, true),
            crossing(11, 6, LegacyOrientation.LEFT, 2, true),
            wall(2, 7, LegacyOrientation.TOP),
            wall(3, 7, LegacyOrientation.BOTTOM),
            conveyor(4, 7, LegacyOrientation.BOTTOM, false),
            conveyor(5, 7, LegacyOrientation.RIGHT, false),
            conveyor(6, 7, LegacyOrientation.TOP, false),
            wall(8, 7, LegacyOrientation.TOP),
            wall(8, 7, LegacyOrientation.BOTTOM),
            wall(9, 7, LegacyOrientation.BOTTOM),
            wall(10, 7, LegacyOrientation.TOP),
            wall(10, 7, LegacyOrientation.RIGHT),
            conveyor(11, 7, LegacyOrientation.BOTTOM, true),
            wall(11, 7, LegacyOrientation.RIGHT),
            wall(0, 8, LegacyOrientation.RIGHT),
            wall(1, 8, LegacyOrientation.LEFT),
            wall(2, 8, LegacyOrientation.BOTTOM),
            wall(3, 8, LegacyOrientation.RIGHT),
            press(4, 8, 2),
            wall(4, 8, LegacyOrientation.LEFT),
            wall(5, 8, LegacyOrientation.BOTTOM),
            wall(5, 8, LegacyOrientation.TOP),
            conveyor(6, 8, LegacyOrientation.TOP, false),
            wall(8, 8, LegacyOrientation.BOTTOM),
            wall(9, 8, LegacyOrientation.TOP),
            wall(10, 8, LegacyOrientation.BOTTOM),
            conveyor(11, 8, LegacyOrientation.BOTTOM, true),
            wall(0, 9, LegacyOrientation.LEFT),
            wall(1, 9, LegacyOrientation.TOP),
            wall(1, 9, LegacyOrientation.RIGHT),
            wall(2, 9, LegacyOrientation.LEFT),
            wall(2, 9, LegacyOrientation.RIGHT),
            wall(3, 9, LegacyOrientation.LEFT),
            conveyor(4, 9, LegacyOrientation.BOTTOM, false),
            pit(5, 9),
            wall(5, 9, LegacyOrientation.BOTTOM),
            press(6, 9, 1),
            wall(7, 9, LegacyOrientation.RIGHT),
            wall(8, 9, LegacyOrientation.LEFT),
            wall(8, 9, LegacyOrientation.RIGHT),
            wall(9, 9, LegacyOrientation.LEFT),
            wall(9, 9, LegacyOrientation.BOTTOM),
            conveyor(11, 9, LegacyOrientation.BOTTOM, true),
            wall(11, 9, LegacyOrientation.RIGHT),
            wall(1, 10, LegacyOrientation.BOTTOM),
            wall(2, 10, LegacyOrientation.TOP),
            conveyor(4, 10, LegacyOrientation.BOTTOM, false),
            curve(5, 10, LegacyOrientation.LEFT, 1, false),
            curve(6, 10, LegacyOrientation.TOP, 1, false),
            wall(9, 10, LegacyOrientation.TOP),
            wall(9, 10, LegacyOrientation.RIGHT),
            repair(10, 10, 1),
            crossing(11, 10, LegacyOrientation.BOTTOM, 1, true),
            conveyor(0, 11, LegacyOrientation.RIGHT, true),
            crossing(1, 11, LegacyOrientation.RIGHT, 1, true),
            conveyor(2, 11, LegacyOrientation.RIGHT, true),
            wall(2, 11, LegacyOrientation.TOP),
            wall(2, 11, LegacyOrientation.BOTTOM),
            conveyor(3, 11, LegacyOrientation.RIGHT, true),
            crossing(4, 11, LegacyOrientation.BOTTOM, 3, false),
            wall(4, 11, LegacyOrientation.TOP),
            curve(5, 11, LegacyOrientation.BOTTOM, 2, false),
            pit(6, 11),
            wall(7, 11, LegacyOrientation.TOP),
            wall(9, 11, LegacyOrientation.TOP),
            wall(9, 11, LegacyOrientation.BOTTOM),
            wall(10, 11, LegacyOrientation.RIGHT),
            conveyor(11, 11, LegacyOrientation.BOTTOM, true),
            checkpoint(2, 1, 1),
            checkpoint(9, 10, 2),
            laser(9, 2, LegacyOrientation.TOP, 2),
            laser(3, 3, LegacyOrientation.RIGHT, 1),
            laser(1, 6, LegacyOrientation.BOTTOM, 1),
            laser(2, 7, LegacyOrientation.BOTTOM, 1),
            laser(5, 8, LegacyOrientation.TOP, 1),
            laser(9, 8, LegacyOrientation.BOTTOM, 1),
            laser(2, 9, LegacyOrientation.LEFT, 2),
            laser(8, 9, LegacyOrientation.RIGHT, 2),
            laser(9, 11, LegacyOrientation.TOP, 3)
    );

    static final LegacyBoardSpec MAP6 = spec(
            pit(0, 0),
            conveyor(1, 0, LegacyOrientation.BOTTOM, false),
            wall(2, 0, LegacyOrientation.TOP),
            curve(4, 0, LegacyOrientation.BOTTOM, 1, false),
            curve(5, 0, LegacyOrientation.RIGHT, 2, false),
            conveyor(6, 0, LegacyOrientation.TOP, false),
            pit(11, 0),
            conveyor(0, 1, LegacyOrientation.RIGHT, false),
            crossing(1, 1, LegacyOrientation.BOTTOM, 2, false),
            pit(2, 1),
            wall(2, 1, LegacyOrientation.BOTTOM),
            conveyor(4, 1, LegacyOrientation.BOTTOM, false),
            pit(5, 1),
            conveyor(6, 1, LegacyOrientation.TOP, false),
            pit(8, 1),
            wall(9, 1, LegacyOrientation.RIGHT),
            wall(10, 1, LegacyOrientation.LEFT),
            wall(0, 2, LegacyOrientation.LEFT),
            curve(1, 2, LegacyOrientation.LEFT, 1, false),
            curve(2, 2, LegacyOrientation.BOTTOM, 2, false),
            wall(3, 2, LegacyOrientation.TOP),
            wall(3, 2, LegacyOrientation.RIGHT),
            conveyor(4, 2, LegacyOrientation.BOTTOM, false),
            wall(4, 2, LegacyOrientation.LEFT),
            wall(5, 2, LegacyOrientation.TOP),
            curve(6, 2, LegacyOrientation.TOP, 2, false),
            curve(7, 2, LegacyOrientation.RIGHT, 1, false),
            wall(8, 2, LegacyOrientation.TOP),
            repair(10, 2, 1),
            wall(11, 2, LegacyOrientation.RIGHT),
            wall(0, 3, LegacyOrientation.RIGHT),
            pit(1, 3),
            wall(1, 3, LegacyOrientation.LEFT),
            conveyor(2, 3, LegacyOrientation.BOTTOM, false),
            repair(3, 3, 2),
            wall(3, 3, LegacyOrientation.BOTTOM),
            conveyor(4, 3, LegacyOrientation.BOTTOM, false),
            wall(5, 3, LegacyOrientation.BOTTOM),
            pit(6, 3),
            conveyor(7, 3, LegacyOrientation.TOP, false),
            pit(8, 3),
            wall(8, 3, LegacyOrientation.RIGHT),
            wall(8, 3, LegacyOrientation.BOTTOM),
            wall(9, 3, LegacyOrientation.LEFT),
            pit(10, 3),
            wall(10, 3, LegacyOrientation.RIGHT),
            wall(11, 3, LegacyOrientation.LEFT),
            wall(0, 4, LegacyOrientation.LEFT),
            curve(1, 4, LegacyOrientation.BOTTOM, 1, false),
            curve(2, 4, LegacyOrientation.RIGHT, 2, false),
            wall(2, 4, LegacyOrientation.RIGHT),
            pit(3, 4),
            wall(3, 4, LegacyOrientation.LEFT),
            conveyor(4, 4, LegacyOrientation.BOTTOM, false),
            wall(6, 4, LegacyOrientation.TOP),
            curve(7, 4, LegacyOrientation.TOP, 2, false),
            curve(8, 4, LegacyOrientation.RIGHT, 1, false),
            wall(11, 4, LegacyOrientation.RIGHT),
            conveyor(0, 5, LegacyOrientation.RIGHT, false),
            curve(1, 5, LegacyOrientation.RIGHT, 2, false),
            pit(2, 5),
            wall(3, 5, LegacyOrientation.RIGHT),
            curve(3, 5, LegacyOrientation.BOTTOM, 1, false),
            wall(3, 5, LegacyOrientation.LEFT),
            curve(4, 5, LegacyOrientation.RIGHT, 2, false),
            wall(6, 5, LegacyOrientation.BOTTOM),
            wall(6, 5, LegacyOrientation.RIGHT),
            pit(7, 5),
            wall(7, 5, LegacyOrientation.LEFT),
            curve(8, 5, LegacyOrientation.TOP, 2, false),
            conveyor(9, 5, LegacyOrientation.RIGHT, false),
            conveyor(10, 5, LegacyOrientation.RIGHT, false),
            conveyor(11, 5, LegacyOrientation.RIGHT, false),
            conveyor(0, 6, LegacyOrientation.LEFT, false),
            pit(2, 6),
            conveyor(3, 6, LegacyOrientation.BOTTOM, false),
            pit(4, 6),
            wall(4, 6, LegacyOrientation.TOP),
            pit(5, 6),
            wall(5, 6, LegacyOrientation.RIGHT),
            wall(6, 6, LegacyOrientation.LEFT),
            wall(6, 6, LegacyOrientation.TOP),
            repair(7, 6, 2),
            wall(8, 6, LegacyOrientation.TOP),
            pit(9, 6),
            wall(10, 6, LegacyOrientation.TOP),
            wall(0, 7, LegacyOrientation.LEFT),
            curve(2, 7, LegacyOrientation.BOTTOM, 1, false),
            wall(2, 7, LegacyOrientation.BOTTOM),
            curve(3, 7, LegacyOrientation.RIGHT, 2, false),
            wall(4, 7, LegacyOrientation.BOTTOM),
            wall(6, 7, LegacyOrientation.BOTTOM),
            wall(8, 7, LegacyOrientation.BOTTOM),
            wall(10, 7, LegacyOrientation.BOTTOM),
            wall(10, 7, LegacyOrientation.RIGHT),
            wall(11, 7, LegacyOrientation.RIGHT),
            pit(1, 8),
            conveyor(2, 8, LegacyOrientation.BOTTOM, false),
            pit(3, 8),
            pit(5, 8),
            wall(5, 8, LegacyOrientation.TOP),
            repair(10, 8, 2),
            pit(7, 8),
            wall(7, 8, LegacyOrientation.TOP),
            pit(9, 8),
            wall(9, 8, LegacyOrientation.TOP),
            wall(10, 8, LegacyOrientation.TOP),
            wall(0, 9, LegacyOrientation.LEFT),
            repair(1, 9, 1),
            conveyor(2, 9, LegacyOrientation.BOTTOM, false),
            curve(5, 9, LegacyOrientation.BOTTOM, 1, false),
            wall(5, 9, LegacyOrientation.BOTTOM),
            conveyor(6, 9, LegacyOrientation.RIGHT, false),
            curve(7, 9, LegacyOrientation.RIGHT, 1, false),
            wall(7, 9, LegacyOrientation.BOTTOM),
            wall(9, 9, LegacyOrientation.BOTTOM),
            wall(10, 9, LegacyOrientation.BOTTOM),
            wall(10, 9, LegacyOrientation.RIGHT),
            wall(11, 9, LegacyOrientation.LEFT),
            wall(11, 9, LegacyOrientation.RIGHT),
            curve(1, 10, LegacyOrientation.BOTTOM, 1, false),
            curve(2, 10, LegacyOrientation.RIGHT, 2, false),
            wall(2, 10, LegacyOrientation.TOP),
            wall(3, 10, LegacyOrientation.RIGHT),
            pit(4, 10),
            wall(4, 10, LegacyOrientation.LEFT),
            wall(4, 10, LegacyOrientation.RIGHT),
            conveyor(5, 10, LegacyOrientation.BOTTOM, false),
            wall(5, 10, LegacyOrientation.LEFT),
            pit(6, 10),
            conveyor(7, 10, LegacyOrientation.TOP, false),
            pit(8, 10),
            pit(9, 10),
            curve(10, 10, LegacyOrientation.LEFT, 2, false),
            conveyor(11, 10, LegacyOrientation.LEFT, false),
            conveyor(1, 11, LegacyOrientation.BOTTOM, false),
            wall(2, 11, LegacyOrientation.TOP),
            wall(2, 11, LegacyOrientation.BOTTOM),
            wall(4, 11, LegacyOrientation.TOP),
            conveyor(5, 11, LegacyOrientation.BOTTOM, false),
            curve(6, 11, LegacyOrientation.LEFT, 2, false),
            curve(7, 11, LegacyOrientation.TOP, 1, false),
            wall(7, 11, LegacyOrientation.TOP),
            wall(8, 11, LegacyOrientation.BOTTOM),
            wall(9, 11, LegacyOrientation.TOP),
            conveyor(10, 11, LegacyOrientation.TOP, false),
            pit(11, 11),
            checkpoint(2, 1, 1),
            checkpoint(9, 11, 2),
            laser(5, 3, LegacyOrientation.TOP, 1)
    );

}
